[general]
import = [
  "~/.config/alacritty/colors.toml",
  "~/.config/alacritty/config.toml",
  "~/.config/alacritty/font.toml",
  "~/.config/alacritty/keybindings.toml",
  "~/.config/alacritty/window.toml",
]
